# Generated by Django 3.1.6 on 2022-06-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Name')),
                ('contact_email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(default='', verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='Recipe Name')),
                ('rate_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('rating', models.CharField(max_length=100, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Client Email')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('cuisine', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Scheduled Date')),
                ('time', models.CharField(max_length=100, verbose_name='Scheduled Time')),
                ('mode', models.CharField(max_length=100, verbose_name='Mode of Class')),
                ('regid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flsys.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Scheduled Date')),
                ('time', models.CharField(max_length=100, verbose_name='Scheduled Time')),
                ('mode', models.CharField(max_length=100, verbose_name='Mode of Class')),
                ('regid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flsys.registration')),
            ],
        ),
        migrations.CreateModel(
            name='CookingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100)),
                ('regid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='flsys.registration')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.IntegerField(blank=True, null=True, verbose_name='Number of Tickets')),
                ('payment', models.CharField(max_length=100, verbose_name='Payment Method')),
                ('regid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flsys.registration')),
            ],
        ),
    ]
