# Generated by Django 3.1.6 on 2022-06-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsummary',
            name='regid',
        ),
    ]
