# Generated by Django 3.1.6 on 2022-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flsys', '0003_delete_transactionsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(max_length=20, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=50, verbose_name='Scheduled Time'),
        ),
    ]
