# Generated by Django 3.1.6 on 2022-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flsys', '0004_auto_20220704_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=5, verbose_name='Rating'),
        ),
    ]
